### ISSUE TITLE
Downloader terminates if it encounters a track with no artist

### ISSUE THREAD

**Issue by aptemus** [eexit/youtube-music-library-exporter#1]
My uploads music library is a bit of a hodge podge of files and includes some items like voice notes which don't have an artist.

The Downloader exits with an error on line 125 when trying to pass the artist into addcslashes:

`addcslashes(): Argument #1 ($string) must be of type string, null given`

To get round this, I manually edited the `metadata.json` file to replace `"artist":null` with `"artist":"Not known"`

**Comment by eexit** [comment]
Yes, or you can edit the script and replace:

```php
addcslashes($song['artist'], ':'),
```

By:

```php
addcslashes($song['artist'] ?? 'Unknown artist', ':'),
```
