### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by onupirat** [eexit/youtube-music-library-exporter#2]
![Screenshot_2](https://user-images.githubusercontent.com/57112817/176980612-9fb5cd10-a93f-4491-a777-d0eebdce1b45.png)

**Comment by eexit** [comment]
Hello, did you install the dependencies?

**Comment by onupirat** [comment]
> Hello, did you install the dependencies?

Yes, though i use WSL. What i don't understand is why metadata-extractor is looking for autoload.php in "vendor" folder. There is no such folder in youtube-music-library-exporter.

**Comment by eexit** [comment]
I meant the "PHP dependencies"! Please take a look at the README.

**Comment by onupirat** [comment]
```
brew install yt-dlp/taps/yt-dlp ffmpeg php composer
composer install
```

You mean this? Yes i installed everything.

**Comment by eexit** [comment]
Well, `composer install` should download all PHP deps within a `vendor` sub-directory.

**Comment by onupirat** [comment]
i just installed linux to try it there and i get the same error. I did everything exactly like in your instruction. Maybe you forgot something?
