### ISSUE TITLE
Metadata Extractor returns empty list with no error messages in verbose mode

### ISSUE THREAD

**Issue by gwtaylor** [eexit/youtube-music-library-exporter#3]
I successfully installed the dependencies and ran `compose install` on MacOS 12.6. 

I followed the instructions to save as HTML only (scrolling all the way to the bottom) but I am getting stuck on the metadata export. 

I'm not seeing any errors when I run in verbose mode but the result is empty.

```
(devel) gwtaylor@m1pro youtube-music-library-exporter % ./metadata-extractor -vvv --html-file=./YouTube\ Music.html                                                                                                     (master)youtube-music-library-exporter

YouTube Music Upload Metadata Extractor
=======================================

 Will extract ./metadata.json from ./YouTube Music.html:
    0 [->--------------------------] < 1 sec

 [OK] done
```

The saved HTML file is 44kb and contains some references to titles in my libraries. But if I grep for other titles I don't see them. I wonder if the HTML format has changed since the last update?

**Comment by eexit** [comment]
Hi @gwtaylor,

It's possible, I made this project for a one-time export so it's not up to date and if the HTML structure has changed, feel free to update the script to reflect these changes.

Thanks!

**Comment by gwtaylor** [comment]
@eexit thanks for making this one-time-export script available. I returned to this nearly a year later and was able to make it work. It took me more than another year to document the steps here but I thought I would leave them in case others want to give it a go. #5 seems to have the same issue.

Here's how to get it working:

## Fixing the HTML Export

The key issue was that saving as "HTML only" didn't capture the complete library content. Using Chrome's "Webpage, Single File" option to save as MHTML format proved more effective. Here's the working process:

1. Instead of saving as "HTML only", save the YouTube Music library page as "Webpage, Single File" in Chrome
   - This creates an .mht (MHTML) file containing all the dynamic content
   - Verify you can open this file and see all your songs

2. Convert the .mht file to HTML using [mhtml2html](https://github.com/msindwan/mhtml2html):
   ```bash
   # Install mhtml2html locally
   npm install mhtml2html
   
   # Convert the file
   npx mhtml2html "YouTube Music.mht" "YouTube Music.html"
   ```
   Note: The conversion may take a few minutes depending on library size.

3. Run the metadata extractor as normal:
   ```bash
   ./metadata-extractor -vvv
   ```

## Updating the Downloader Script

The original downloader script relied on the [now-removed "Get Cookies.txt" Chrome extension](https://www.reddit.com/r/youtubedl/comments/10ar7o7/if_youve_been_using_the_get_cookiestxt_chrome/). Instead, we can use yt-dlp's built-in browser cookie support. Here's the patch to update the downloader script:

```diff
--- downloader	2022-10-08 11:49:14
+++ downloader1	2023-09-04 14:49:58
@@ -49,12 +49,6 @@
             return Command::INVALID;
         }
-        if (!file_exists($input->getOption('cookies-file'))) {
-            $io->error('cookies-file not found');
-
-            return Command::INVALID;
-        }
-
         $argSongId = $input->getOption('song-id');
         if ($argSongId) {
@@ -85,7 +79,7 @@
         --no-warnings
         --no-progress
         --no-mtime
-        --cookies "%s"
+        --cookies-from-browser chrome
         --parse-metadata " %s: %%(meta_artist)s"
         %s
         --embed-metadata
@@ -121,7 +115,6 @@
                     sprintf(
                         $cmdTemplate,
                         $ytdlp,
-                        $cookiesFile,
                         addcslashes($song['artist'], ':'),
                         $song['album'] ? sprintf($albumTemplate, addcslashes($song['album'], ':')) : '',
                         $outputDir.DIRECTORY_SEPARATOR.$song['id'],
```

To apply these changes:
1. Make a backup of your original `downloader` script
2. Apply the patch above using your preferred method (or manually make the changes)
3. Make sure you're logged into YouTube Music in Chrome
4. Run the downloader script (it will now pull cookies directly from Chrome)

## Notes and Caveats

- This solution was tested with YouTube Music's interface as of September 2023
- The downloader will use your Chrome browser's cookies, so make sure you're logged into YouTube Music in Chrome
- Keep the default `./downloads` output directory to avoid path escaping issues
- The conversion from MHTML to HTML may take several minutes for large libraries

This solution should work as long as you:
1. Capture the complete page state using MHTML
2. Convert it properly to HTML
3. Use the updated downloader script with browser cookie support

Remember to verify your `metadata.json` file contains the expected entries before starting the download process.

## Final Step: Clustering

After successfully running the downloader script and getting all your files in the `./downloads` directory, you can proceed with the clustering step as described in the original README. The `clusterer` script works without any modifications needed.
